### ISSUE TITLE
websockets:serve is called even when the beyondcode/laravel-websockets package is not installed.

### ISSUE THREAD

**Issue by LukeTowers** [NativePHP/electron-plugin#3]
<img width="1728" alt="Screenshot 2023-07-23 at 9 09 51 PM" src="https://github.com/NativePHP/electron-plugin/assets/7253840/ea29d9ff-1f0e-434c-89b1-542b2660e48b">

See https://github.com/NativePHP/electron-plugin/blob/main/src/server/websockets.ts#L6-L8

**Comment by mpociot** [comment]
Fixed in https://github.com/NativePHP/electron-plugin/commit/adbfd459e517fc063b0ec45217a363f901bb4469
